### ISSUE TITLE
Variable Substitution

### ISSUE THREAD

**Issue by x0139** [tailhook/trafaret-config#9]
Greetings!
I have a problems with Variable Substitution.
Got one of yaml parameter like "$ERF", and when applications start, got error 
"variable 'ERF' not found"
Try to do like this:
`config = commandline.config_from_options(options, TRAFARET, vars=None)`
but in this case got another error:

>     replaced[key] = self.__vars.get(key)
> AttributeError: 'NoneType' object has no attribute 'get'

Installed version:
trafaret-1.2.0
trafaret-config-2.0.1

**Comment by tailhook** [comment]
Fixed in v2.0.2, thanks for the report!

By the way, if you want to substitute some vars, but also leave other `$things` intact in the config, you can pass some special dict in vars. I.e. one which substitutes known/unknown variables to dollar-name. This requires to know which variables must be substituted and which must be left intact, though.
